// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

// 1. Destructure your variables from process.env
const {
  DB_HOST,
  DB_PORT,
  DB_USERNAME,
  DB_PASSWORD,
  DB_NAME
} = process.env;


const passwordPart = DB_PASSWORD ? `:${DB_PASSWORD}` : '';

// 3. Construct the final URL
const databaseUrl = `mysql://${DB_USERNAME}${passwordPart}@${DB_HOST}:${DB_PORT}/${DB_NAME}`;

process.env.DATABASE_URL = databaseUrl;
export default defineConfig({
  schema: "prisma/schema.prisma",
  // migrations: {
  //   path: "prisma/migrations",
  // },
  // datasource: {
  //   url: databaseUrl,
  // }
});
